simulator_name: "mobl_arms_unity_demo"

simulation:
  bm_model:
    cls: "MoblArms"
    kwargs:
      shoulder_variant: "none"
  task:
    cls: "UnityDemo"
    kwargs:
      unity_executable: "/home/aleksi/Workspace/unity-exergame/build/build.x86_64"
      end_effector: "hand"
      relpose: [-0.01772321, 0.01274328, -0.07052886, 0.7901813, -0.3503278, -0.4854591, 0.1311998]
      controller_right_position: [0.05, -0.21, 0.39]
      controller_right_quaternion: [-0.0770075, -0.8572073, -0.1352977, -0.4908768]  # -180 60 -18-
#      root_name: "thorax"
#      root_position: [0, 0, 0]
#      root_quaternion: [0.525322, 0, 0.8509035, 0]
  perception_modules:
    - cls: "vision.UnityHeadset"
      kwargs:
        resolution: [120, 80] # must match dimensions used in unity
        channels: [1]
        buffer: 0.1
    - cls: "proprioception.BasicWithEndEffectorPosition"
      kwargs:
        end_effector: ["geom", "hand_2distph"]
  run_parameters:
    action_sample_freq: 20

rl:
  algorithm: "PPO"
  policy_type: "policies.MultiInputActorCriticPolicyTanhActions"
  policy_kwargs:
    activation_fn: "torch.nn.LeakyReLU"
    net_arch: [256, 256, 256]
    log_std_init: 0.0
    features_extractor_class: "feature_extractor.FeatureExtractor"
    normalize_images: False
  lr: 
    function: "schedule.linear_schedule"
    kwargs:
      initial_value: 5e-5
      min_value: 1e-7
      threshold: 0.8
  total_timesteps: 100_000_000
  device: "cuda"
  num_workers: 6
  nsteps: 4000
  batch_size: 1000
  target_kl: 1.0
  save_freq: 5_000_000